/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.onboard.cinema.book.show.kafka.booking.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum CinemaBookingStatus implements org.apache.avro.generic.GenericEnumSymbol<CinemaBookingStatus> {
  PAID  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CinemaBookingStatus\",\"namespace\":\"com.onboard.cinema.book.show.kafka.booking.avro.model\",\"symbols\":[\"PAID\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
